id: P010664
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:18:51.979816
source_metadata:
  id: bdr:W8LS17358
  title: བླ་མ་མཆོད་པའི་ཚོགས་མཆོད།
  author: ''
  volumes:
    65cd27d67c924d159081543b5ffd16a4:
      image_group_id: I8LS17368
      title: ''
      volume_number: 1
      total_pages: 60
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
